### ISSUE TITLE
"npm i --save react-native-beautiful-video-recorder" shows errors

### ISSUE THREAD

**Issue by turbozv** [phuochau/react-native-beautiful-video-recorder#1]
Hi Hau,

Thanks for making this video recorder, I have issue installing it, could you please help?

[Repro steps]
react-native init videoCapture
cd videoCapture
npm i --save react-native-beautiful-video-recorder

[Expect]
Install ok

[Actual]
videoCapture@0.0.1 C:\Users\turbo_000\Desktop\video\videoCapture
+-- UNMET PEER DEPENDENCY react-native@0.44.0
+-- react-native-beautiful-video-recorder@1.2.0
+-- UNMET PEER DEPENDENCY react-native-camera@git+https://github.com/lwansbrough/react-native-camera.git
+-- UNMET PEER DEPENDENCY react-native-compress@^1.0.2
+-- UNMET PEER DEPENDENCY react-native-spinkit@^1.0.2
`-- UNMET PEER DEPENDENCY react-native-vector-icons@^4.0.0

npm WARN react-native-beautiful-video-recorder@1.2.0 requires a peer of react-native@^0.43.3 but none was installed.
npm WARN react-native-beautiful-video-recorder@1.2.0 requires a peer of react-native-camera@git+https://github.com/lwansbrough/react-native-camera.git but none was installed.
npm WARN react-native-beautiful-video-recorder@1.2.0 requires a peer of react-native-vector-icons@^4.0.0 but none was installed.
npm WARN react-native-beautiful-video-recorder@1.2.0 requires a peer of react-native-spinkit@^1.0.2 but none was installed.
npm WARN react-native-beautiful-video-recorder@1.2.0 requires a peer of react-native-compress@^1.0.2 but none was installed.

**Comment by phuochau** [comment]
Hi @turbozv , let's install peer dependency packages:
`npm i react-native-camera react-native-compress react-native-spinkit react-native-vector-icons -S`

After that, link them:
`react-native link`

I will update the docs later.

**Comment by turbozv** [comment]
thanks @phuochau ! let me try that!

**Comment by turbozv** [comment]
After manually "npm install" the packages, npm is good.

Then I added the sample code and see this. Any ideas?
![simulator screen shot may 9 2017 8 58 27 pm](https://cloud.githubusercontent.com/assets/26913052/25882904/4d99a974-34fb-11e7-957a-d147b39be966.png)

**Comment by phuochau** [comment]
Hi @turbozv is it okay right now? Because I haven't tested with 0.44 yet.

**Comment by jgattegno** [comment]
not working, similar issue
