### ISSUE TITLE
Build failed: Unable to resolve module 'moment'

### ISSUE THREAD

**Issue by nappyturtle** [phuochau/react-native-beautiful-video-recorder#11]
Error: bundling failed: Error: Unable to resolve module

Module `moment` does not exist in the Haste module map

**Comment by luvnish19** [comment]
Same issue I am also getting. Is there any way to resolve it??

**Comment by yuyongmao** [comment]
me too

**Comment by yuyongmao** [comment]
just run 'yarn add moment' can solve this problem 
but get a new problem

**Comment by wolfjobs** [comment]
`"react": "^16.5.0",
    "react-native": "^0.56.0",`

**Comment by jesem325** [comment]
Same issue I am also getting. Is there any way to resolve it??
