### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by DanielMSchmidt** [phuochau/react-native-beautiful-video-recorder#13]
Hey there,

Thank you for this awesome library. Unfortunately, it doesn't work with the newest React Native, at least the version published on npm. Could you update it to reflect the recent changes that allow compatibility with `prop-types` (they were removed from React)

**Comment by phuochau** [comment]
@DanielMSchmidt Sorry because I have busy for a while, I will try to make new version as soon as possible

**Comment by DanielMSchmidt** [comment]
Thank you for your time!

**Comment by imadarif** [comment]
new version is not pushed.
