### ISSUE TITLE
undefined is not an object

### ISSUE THREAD

**Issue by Jeijie** [phuochau/react-native-beautiful-video-recorder#15]
An error occured "undefined is not an object(evaluating '_react2.PropTypes.bool)"

![image](https://user-images.githubusercontent.com/9338052/51647589-5c084480-1fb8-11e9-98ee-fe614507d2f0.png)

"react-native-beautiful-video-recorder": "^1.2.0",

Environment:
  OS: macOS High Sierra 10.13.6
  Node: 8.11.3
  Yarn: 1.9.4
  npm: 6.3.0
  Watchman: 4.9.0
  Xcode: Xcode 10.1 Build version 10B61
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

**Comment by sajid086** [comment]
same issue here, any luck ?

**Comment by Pardeep03315** [comment]
Just run this command 
 npm install prop-types --save 
and
   go to node-modules react-native-comress and react-native-spinkit 
   and 
 then replace propsTypes imported from react with 
  import PropTypes from 'prop-types';
from all the js files in these libararies ....Hope its help thanks
