### ISSUE TITLE
How to play recorded video

### ISSUE THREAD

**Issue by Adar-Li** [phuochau/react-native-beautiful-video-recorder#2]
Video recording is successful, but want to preview, how should do?
thanks

**Comment by phuochau** [comment]
Hi @Adar-Li currently, this module doesn't support for playback. But you can use [react-native-video](https://github.com/react-native-community/react-native-video/) to play it.

**Comment by Adar-Li** [comment]
@phuochau thanks

**Comment by Adar-Li** [comment]
@phuochau Whether can the android recorded video compression？

**Comment by phuochau** [comment]
@Adar-Li it doesn't support right now, I will plan to do it later.

**Comment by Adar-Li** [comment]
@phuochau thanks
