### ISSUE TITLE
After unlink & uninstall there are still references to -lRNMov2mp4

### ISSUE THREAD

**Issue by sunnypatel** [phuochau/react-native-beautiful-video-recorder#4]
I tried to remove this package by doing the following
```
react-native unlink react-native-beautiful-video-recorder
npm uninstall --save react-native-beautiful-video-recorder
```
When I attempt to do a release build of my RN project now I'm getting
```
ld: library not found for -lRNMov2mp4
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Seems it's not cleaning up everything.
I've tried doing a Project Clean in xcode.

**Comment by phuochau** [comment]
@sunnypatel sorry for late response, because I just came back from a trip. You can go to `Build Phases` and remove `RNMov2mp4`. That's all
