### ISSUE TITLE
Plugin issue

### ISSUE THREAD

**Issue by ArpitOTS** [phuochau/react-native-beautiful-video-recorder#5]
After running the the following 

npm i --save react-native-beautiful-video-recorder

The plugin was not installed properly there were some warnings due which elements are missing. After there was another command  for linking the module I guess "react-native link" it worked fine. But after that when I tried to run my code after adding this line as asked 

import VideoRecorder from 'react-native-beautiful-video-recorder';

It throughs an error I am attaching of my simulator for the same. If needed I can also put the errors that I got while installing the plugin.

Thanks in Advance.

![simulator screen shot 04-aug-2017 5 35 00 pm](https://user-images.githubusercontent.com/24451260/28967946-47dca066-793b-11e7-95ce-2e7b48ea7d24.png)

**Comment by phuochau** [comment]
@ArpitOTS just install moment.js by `yarn add moment`
