### ISSUE TITLE
Not working and i want to create a video recorder in react native and i got this error

### ISSUE THREAD

**Issue by Fermi-Android** [phuochau/react-native-beautiful-video-recorder#6]
The development server returned response error code: 500

URL: http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false

Body:
{"message":"TransformError: /media/znt/Office/Ekta_Tekpreneur/React_native/VideoRecoder/node_modules/moment/moment.js: require() must have a single string literal argument","type":"TransformError","lineNumber":0,"description":"","errors":[{"description":"","lineNumber":0}]}
processBundleResult
    BundleDownloader.java:170
access$100
    BundleDownloader.java:39
onResponse
    BundleDownloader.java:139
execute
    RealCall.java:135
run
    NamedRunnable.java:32
runWorker
    ThreadPoolExecutor.java:1162
run
    ThreadPoolExecutor.java:636
run
    Thread.java:764

**Comment by phuochau** [comment]
Seem it's an issue with momentjs: https://github.com/moment/moment/pull/4187 . I will follow and update soon
