### ISSUE TITLE
Cannot find module 'react-native-beautiful-video-recorder'

### ISSUE THREAD

**Issue by oferRounds** [phuochau/react-native-beautiful-video-recorder#7]
Any idea? I do see it there...

And thanks for this library!

**Comment by oferRounds** [comment]
If I‘m using `require` instead of `import` I get:

`Unhandled JS Exception: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
Check the render method of 'VideoScreenRecorder'.`

**Comment by oferRounds** [comment]
After removing the `default` from the `VideoRecorder` declaration, I get 2 errors:
- `Unhandled JS Exception: RawText " // quality will be 'low', 'medium' or 'high'" must be wrapped in an explicit <Text> component.`
- `Exception 'shadowView super (of ID 17) not found' was thrown while invoking replaceExistingNonRootView on target UIManager with params (
    17,
    18
)`

**Comment by fazeelzama20** [comment]
after installation when i am importing the library with 
`import VideoRecorder from 'react-native-beautiful-video-recorder';` statement, it gives the error of 'Failed to execute 'importScript''
